### ISSUE TITLE
Cannot extend key tables

### ISSUE THREAD

**Issue by robrecord** [twilsoft/wezmode#3]
Hi there,

I'm using custom key tables and I tried extending the keytables as you did with keys, but I get the error: 

```
error converting Lua table to config::config::Config 
(Error processing Config::key_tables: Cannot convert `Array` to `HashMap`)
```

My config is like this:

```
key_tables = wezmode.extendTable({
  copy_mode = {
...
  },
}, wezmode.getKeyTables()),
```

**Comment by jakenvac** [comment]
Hey, thanks for raising an issue. Could you share your full config, wezmode & wezterm? Or at least a setup that reproduces the issue? I'll test it and let you know what I find.
